name: SlowAreaTp
version: '1.1'
main: plugin.slowAreaTp.SlowAreaTp
api-version: '1.21'
authors: [ Jxst_Kirito ]

commands:
  gebiete:
    description: Öffnet ein GUI zum Teleportieren zu verschiedenen Gebieten
    usage: /gebiete

permission:
  gebiete.open:
    description: Erlaubt es dem Spieler, das GUI zu benutzen
    default: true
